## Intro

In this PA, you will practice altering data frame objects in order to solve a riddle.

### Advice for troubleshooting your code

#### Check results often

If a chunk of code runs smoothly without giving you any error or warnings this does not necessarily mean it accomplished the desired task.

It is a good habit to check the results of your code every time you finish a task.

If you created or updated a data frame, make sure your edits did what you hoped.  Use the *Environment* or the `head()` function to investigate your changes.

#### Document your work

In the text before the code chunk, make sure to briefly state what the point of the chunk is.  This will remind later readers - which might be your future self! - what the desired output is.

Use comments in the code to give quick explanations of the goals of complex steps.

#### Two heads are better than one

It can be hard to spot bugs in code that you yourself wrote.t
(Have you ever sent a text message and not spotted an obvious  typo?  Same idea!)

Work with people around you if you can - if something goes wrong, ask a friend to take a peek at your code and see if any glaring errors (like *syntax error*) pop out.

#### Explain your code out loud

The best way to troubleshoot a sneaky bug is to explain out loud each step of your code, and what you hoped to accomplish.

If you are alone, try [Rubber Duck Debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging)!

#### Google is your friend

The whole of the internet is at your disposal!  Use it early, use it often.

Copy-paste the exact error message into Google. Chances are, somebody else had a similar problem and got a similar message.


Include package names in your search terms.  For example, "bar plot in plotnine with pandas data frame" is a better search than "bar plot in python".


## Part One: Data import and cleaning

This section will walk you through some steps to clean up today's dataset, so that you can use it more easily in Part Two.  

First, we declare our package dependencies and load the data.

(Note that the data loading function `read_csv` will give you an outpouring of helpful information about the dataset.  If you do not see the word "error", there is nothing to be concerned about.)

In [ ]:
import numpy as np
import pandas as pd

colleges = pd.read_csv("https://www.dropbox.com/s/bt5hvctdevhbq6j/colleges.csv?dl=1")

The code chunks in this section will cause an error and/or do the desired task incorrectly.  (Even the chunks that run without error are not correct!) You will need to find the mistake, and correct it, to complete the intended action.

None of the *text* is incorrect, only the *code* - your goal is to make the code do exactly what the documentation claims it will.

#### 1. Narrow down the columns to variables of interest

There are too many variables in this dataset.  We don't need all of them. We will limit our dataset down to only:

Name of the institution
City, State, and ZIP code of the institution
The Admissions Rate
The average SAT score
The number of undergraduate students
The in and out of state tuitions
Whether the school is public or private
The "REGION" variable.

In [ ]:
colleges_clean = colleges[['INSTNM', 'CITY', 'STABBR', 'ZIP', 'CONTROL', 'ADM_RATE', 'SAT_AVG', 'TUITIONFEE_IN', 'TUITIONFEE_OUT', 'UGDS', 'REGION']] # double brackets to return dataframe with mult columns, single returns series

colleges_clean

,INSTNM,CITY,STABBR,ZIP,CONTROL,ADM_RATE,SAT_AVG,TUITIONFEE_IN,TUITIONFEE_OUT,UGDS,REGION
0,Alabama A & M University,Normal,AL,35762,1,0.9027,929.0,9857.0,18236.0,4824.0,5
1,University of Alabama at Birmingham,Birmingham,AL,35294-0110,1,0.9181,1195.0,8328.0,19032.0,12866.0,5
2,Amridge University,Montgomery,AL,36117-3553,2,NaN,NaN,6900.0,6900.0,322.0,5
3,University of Alabama in Huntsville,Huntsville,AL,35899,1,0.8123,1322.0,10280.0,21480.0,6917.0,5
4,Alabama State University,Montgomery,AL,36104-0271,1,0.9787,935.0,11068.0,19396.0,4189.0,5
...,...,...,...,...,...,...,...,...,...,...,...
7053,Arizona State University at Yuma,Yuma,AZ,853656900,1,NaN,NaN,NaN,NaN,NaN,6
7054,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,3,NaN,NaN,NaN,NaN,NaN,8
7055,High Desert Medical College,Lancaster,CA,935340000,3,NaN,NaN,NaN,NaN,NaN,8
7056,BCI - Malden,Malden,MA,21480000,2,NaN,NaN,NaN,NaN,NaN,1
7057,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,333137268,3,NaN,NaN,22575.0,NaN,NaN,5

#### 2. Remove observations that aren't needed

Drop the schools that are "private for-profit" (category 3).  We will not need these for the puzzle.

In [ ]:
colleges_clean = colleges_clean[colleges_clean['CONTROL'] != 3] #filters out all row variables that return 3 (which is private for-profit); ! gives the not equal to 3
colleges_clean

,INSTNM,CITY,STABBR,ZIP,CONTROL,ADM_RATE,SAT_AVG,TUITIONFEE_IN,TUITIONFEE_OUT,UGDS,REGION
0,Alabama A & M University,Normal,AL,35762,1,0.9027,929.0,9857.0,18236.0,4824.0,5
1,University of Alabama at Birmingham,Birmingham,AL,35294-0110,1,0.9181,1195.0,8328.0,19032.0,12866.0,5
2,Amridge University,Montgomery,AL,36117-3553,2,NaN,NaN,6900.0,6900.0,322.0,5
3,University of Alabama in Huntsville,Huntsville,AL,35899,1,0.8123,1322.0,10280.0,21480.0,6917.0,5
4,Alabama State University,Montgomery,AL,36104-0271,1,0.9787,935.0,11068.0,19396.0,4189.0,5
...,...,...,...,...,...,...,...,...,...,...,...
7050,Arizona State University at Tucson,Tucson,AZ,857454284,1,NaN,NaN,NaN,NaN,NaN,6
7051,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,1,NaN,NaN,6904.0,10106.0,NaN,6
7052,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,1,NaN,NaN,NaN,NaN,NaN,6
7053,Arizona State University at Yuma,Yuma,AZ,853656900,1,NaN,NaN,NaN,NaN,NaN,6
7056,BCI - Malden,Malden,MA,21480000,2,NaN,NaN,NaN,NaN,NaN,1

### 3. Adjust variable types: Numeric

Some of the columns of the dataset were automatically understood by the computer to be categorical, due to missing data appearing like strings.

Adjust the appropriate columns to be numeric.

In [ ]:
colleges_clean['TUITIONFEE_IN'] = colleges_clean['TUITIONFEE_IN'].astype('float')

colleges_clean['TUITIONFEE_OUT'] = colleges_clean['TUITIONFEE_OUT'].astype('float')

colleges_clean['SAT_AVG'] = colleges_clean['SAT_AVG'].astype('float')

colleges_clean['ADM_RATE'] = colleges_clean['ADM_RATE'].astype('float')

/tmp/ipython-input-990583193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colleges_clean['TUITIONFEE_IN'] = colleges_clean['TUITIONFEE_IN'].astype('float')
/tmp/ipython-input-990583193.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colleges_clean['TUITIONFEE_OUT'] = colleges_clean['TUITIONFEE_OUT'].astype('float')
/tmp/ipython-input-990583193.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colleges_clean['SAT_AVG'] = colleges_clean['SAT_AVG'].astype('float')
/tmp/ipython-input-990583193.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colleges_clean['ADM_RATE'] = colleges_clean['ADM_RATE'].astype('float')

In [ ]:
colleges_clean.dtypes

INSTNM             object
CITY               object
STABBR             object
ZIP                object
CONTROL             int64
ADM_RATE          float64
SAT_AVG           float64
TUITIONFEE_IN     float64
TUITIONFEE_OUT    float64
UGDS              float64
REGION              int64
dtype: object

### 4. Adjust variable types: Categorical

Similarly, columns of the dataset that are not numbers are automatically understood by the computer to be strings.

We know, however, that some variables are truly *categorical*, in that there are only a few categories (or "levels") that can be values of the column.

Adjust the appropriate columns to be understood as categorical.

In [ ]:
colleges_clean['CONTROL'].astype('category')
colleges_clean['REGION'].astype('category')
colleges_clean['STABBR'].astype('category')

0       AL
1       AL
2       AL
3       AL
4       AL
        ..
7050    AZ
7051    AZ
7052    AZ
7053    AZ
7056    MA
Name: STABBR, Length: 4089, dtype: category
Categories (59, object): ['AK', 'AL', 'AR', 'AS', ..., 'WA', 'WI', 'WV', 'WY']

#### 5. Calculate new variables

Create a new variable called TUITION_DIFF which contains the difference between in and out of state costs.

In [ ]:
colleges_clean['TUITION_DIFF'] = colleges_clean['TUITIONFEE_OUT'] - colleges_clean['TUITIONFEE_IN']

/tmp/ipython-input-721408952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colleges_clean['TUITION_DIFF'] = colleges_clean['TUITIONFEE_OUT'] - colleges_clean['TUITIONFEE_IN']

In [ ]:
colleges_clean.head()

,INSTNM,CITY,STABBR,ZIP,CONTROL,ADM_RATE,SAT_AVG,TUITIONFEE_IN,TUITIONFEE_OUT,UGDS,REGION,TUITION_DIFF
0,Alabama A & M University,Normal,AL,35762,1,0.9027,929.0,9857.0,18236.0,4824.0,5,8379.0
1,University of Alabama at Birmingham,Birmingham,AL,35294-0110,1,0.9181,1195.0,8328.0,19032.0,12866.0,5,10704.0
2,Amridge University,Montgomery,AL,36117-3553,2,NaN,NaN,6900.0,6900.0,322.0,5,0.0
3,University of Alabama in Huntsville,Huntsville,AL,35899,1,0.8123,1322.0,10280.0,21480.0,6917.0,5,11200.0
4,Alabama State University,Montgomery,AL,36104-0271,1,0.9787,935.0,11068.0,19396.0,4189.0,5,8328.0

#### 6. Deal with missing data

Drop all the rows with missing data.

(It is often a terrible idea to simply drop all rows with *any* missing data!  Usually, even if *some* of the information is missing, we don't want to throw out the entire row.  In this example, however, we'll be lazy.)

In [ ]:
colleges_clean = colleges_clean.dropna(axis = 0) #0 drops rows with empty data, 1 drops columns with empty data

## Part Two:  Identify the mystery college

Wow!  Your best friend Ephelia has been accepted to the college of her dreams!  Unfortunately, Ephelia is a very mysterious person, and she won't tell you directly which college this is.  You'll have to use her clues to figure out which school is her dream school.

Clues:

1. This college is located in Region 1.

2. This college's admission rate is in the first quartile for the region.

3. This college charges the same for in- and out-of-state tuition.

4. The average SAT score of this college is an odd number.

5. This college is NOT in New Hampshire or in the city of Boston.

6. More than 3,000 people apply to this college every year.  (Hint: Make a new variable to compute how many people apply.  Assume the size of an incoming class is 1/4 of the total undergraduate population, and remember that not everyone who *applies* is *admitted*.)

7. Ephelia is not going to an Ivy League school.

8. Of the two options remaining at this step, Ephelia will attend the cheaper one.

In [ ]:
colleges_clean = colleges_clean[colleges_clean['REGION'] == 1] #1

colleges_clean = colleges_clean[colleges_clean['ADM_RATE'] < colleges_clean['ADM_RATE'].quantile(0.25)]  #2, used ChatGPT to figure out the .quantile(.25)


colleges_clean = colleges_clean[colleges_clean['TUITION_DIFF'] == 0] #3

colleges_clean = colleges_clean[colleges_clean['SAT_AVG'] % 2 == 1] #4

colleges_clean = colleges_clean[colleges_clean['CITY'] != 'Boston'] #5

colleges_clean = colleges_clean[colleges_clean['STABBR'] != 'NH'] #5

colleges_clean['EST_APPLICANTS'] = (colleges_clean['UGDS'] * 0.25) / colleges_clean['ADM_RATE'] #6

colleges_clean = colleges_clean[colleges_clean['EST_APPLICANTS'] > 3000] #6

colleges_clean

,INSTNM,CITY,STABBR,ZIP,CONTROL,ADM_RATE,SAT_AVG,TUITIONFEE_IN,TUITIONFEE_OUT,UGDS,REGION,TUITION_DIFF,EST_APPLICANTS
1500,Amherst College,Amherst,MA,01002-5000,2,0.1290,1497.0,54310.0,54310.0,1835.0,1,0.0,3556.201550
1549,Harvard University,Cambridge,MA,2138,2,0.0516,1523.0,48949.0,48949.0,7532.0,1,0.0,36492.248062
1619,Williams College,Williamstown,MA,1267,2,0.1458,1493.0,53550.0,53550.0,2033.0,1,0.0,3485.939643

In [ ]:
colleges_clean = colleges_clean[colleges_clean['REGION'] == 1]
colleges_clean['ADM_RATE'].quantile(.25)

np.float64(0.4789)